package com.example.cinematime;

import java.util.Arrays;
import java.util.List;

public class MovieManager {
    public static final List<Movie> movieList = Arrays.asList(
            new Movie(1,
                    "The Tourist",
                    "An american romantic thriller film. During an impromptu trip to Europe to mend a broken heart, math teacher Frank Tupelo (Johnny Depp) finds himself in an extraordinary situation when an alluring stranger, Elise (Angelina Jolie), places herself in his path. Their seemingly innocent flirtation turns into a dangerous game of cat and mouse while various people, who all think that Frank is Elise's thieving paramour, Alexander Pearce, try to capture the pair..",
                    2010,
                    Arrays.asList("Angelina Jolie", "Johnny Depp", "Paul Bettany", "Timothy Dalton"),
                    R.drawable.the_tourist,
                    R.raw.the_tourist_trauler),
            new Movie(2,
                    "Dear John",
                    "An american romantic war drama film – it follows the life of a soldier (Channing Tatum) after he falls in love with a young woman (Amanda Seyfried). They decide to exchange letters to each other after he is deployed to the war.",
                    2010,
                    Arrays.asList("Channing Tatum", "Amanda Seyfried"),
                    R.drawable.dear_john,
                    R.raw.dear_john_trailer),
            new Movie(3,
                    "Pretty Woman",
                    "An American romantic comedy film. The film's story centers on Hollywood prostitute Vivian Ward and wealthy businessman Edward Lewis. Vivian is hired to be Edward's escort for several business and social functions, and their relationship develops during her week-long stay with him.",
                    1990,
                    Arrays.asList("Julia Roberts", "Richard Gere", "Héctor Elizondo", "Ralph Bellamy"),
                    R.drawable.pretty_woman,
                    R.raw.pertty_woman_trailer),
            new Movie(4,
                    "Skyfall",
                    "An American spy film – The twenty-third in the James Bond series. James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.",
                    2012,
                    Arrays.asList("Daniel Craig", "Javier Bardem",  "Raoul Silva"),
                    R.drawable.skyfall,
                    R.raw.skyfall_trailer),
            new Movie(5,
                    "Aquaman",
                    "An American superhero film. Arthur Curry / Aquaman, who sets out to lead the underwater kingdom of Atlantis and stop his half-brother, King Orm, from uniting the seven underwater kingdoms to destroy the surface world.",
                    2018,
                    Arrays.asList("David Leslie", "David Leslie", "Willem Dafoe", "Patrick Wilson"),
                    R.drawable.aqua_man,
                    R.raw.aquaman_trailer),
            new Movie(6,
                    "Aladdin",
                    "An American musical fantasy film. it is a live-action adaptation of Disney's 1992 animated film of the same name, The plot follows Aladdin, a street urchin, as he falls in love with Princess Jasmine, befriends a wish-granting genie, and battles the wicked sorcerer Jafar.",
                    2019,
                    Arrays.asList("Will Smith", "Mena Massoud", "Naomi Scott", "Marwan Kenzari"),
                    R.drawable.aladin,
                    R.raw.aladdin_trailer),
            new Movie(7,
                    "Maleficent",
                    "An American fantasy film. the film is a live action retelling of Walt Disney's 1959 animated film Sleeping Beauty, and portrays the story from the perspective of the eponymous antagonist, depicting her conflicted relationship with the king and princess of a corrupt kingdom.",
                    2014,
                    Arrays.asList("Angelina Jolie",  "Sharlto Copley", "Elle Fanning", "Sam Riley"),
                    R.drawable.maleficent,
                    R.raw.maleficent_trailer),
            new Movie(8,
                    "The Lion King",
                    "An American musical drama film. It is a photorealistic computer-animated remake of Disney's traditionally animated 1994 film of the same name. The plot follows Simba, a young lion who must embrace his role as the rightful king of his homeland following the murder of his father, Mufasa, at the hands of his uncle, Scar.",
                    2019,
                    Arrays.asList("Donald Glover", "Seth Rogen", "Chiwetel Ejiofor", "Alfre Woodard"),
                    R.drawable.the_lion_king,
                    R.raw.the_lion_king_trailer)
    );
}
